import os

CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")
PLAYLIST_ID = f'spotify:playlist:{os.getenv("SPOTIFY_KOALATREEHOUSE23_PLAYLIST_ID")}'
